version: '3.8'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"       # S3 endpoint
      - "9001:9001"       # MinIO web UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  postgres:
    image: postgres:14
    container_name: postgres_pet_mood
    restart: always
    environment:
      POSTGRES_USER: ihab
      POSTGRES_PASSWORD: ihab123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d


volumes:
  minio_data:
  postgres_data: